### ISSUE TITLE
Tableau Desktop can't connect to the TabPy service

### ISSUE THREAD

**Issue by Siz001** [tableau/TabPy#27]
Hi All, 
I have installed TabPy service on my Windows 7 machine as stated. I started the service through Administrator cmd and its running on Port 9004. The browser is showing the tableau icon on http://localhost:9004 and i can see the service running using netstat -na at the same port. 
When I use External Service Connection Dialog inside Tableau 10.2.0 to test this connection it says "an error occurred while communication...." The details are 
External Service: The external server is busy or not responding. Failed to create socket to it. ExtSvc: 504:<HEAD><TITLE>Unknown Host</TITLE></HEAD> <BODY BGCOLOR="white" FGCOLOR="black"><H1>Unknown Host</H1><HR> <FONT FACE="Helvetica,Arial"><B> Description: Unable to locate the server named "<em>localhost</em>" --- the server does not have a DNS entry. Perhaps there is a misspelling in the server name, or the server no longer exists. Double-check the name and try again.</B></FONT> <HR>  </BODY>

Any help?
Thanks!

**Comment by BBeran** [comment]
It looks like localhost doesn't resolve to 127.0.0.1

You can try using http://127.0.0.1     in the dialog instead of http://localhost

Doing the following addition

127.0.0.1 localhost

to hosts file, located in C:/Windows/System32/drivers/etc/hosts  can also help.

I hope this helps,

Bora

**Comment by vijaykumarsh** [comment]
Hello @BBeran  : I get the below error while connecting Tableau and Python...
Tabpy server has started, but while connecting Tableau to python using "External Service Connection"
I get the this error, could you please help me in resolving this

"
External Service: IPC_Network::Resolve(hostname="http://127.0.0.1"): The requested name is valid, but no data of the requested type was found ExtSvc: 403:<html> <head> <title>Access Denied</title> <style type="text/css">  </style> </head> <body> <div class="container"> <h1>Access Denied</h1> An access request has been blocked due to one of the following reasons: <ul> <li>You do not have sufficient privileges to access this destination</li> <li>Your corporate IT policies prohibit access to this content or application</li> <li>McAfee Global Threat Intelligence has determined</li> <ul> <li>this destination to have a suspicious or malicious reputation at this time </li> <li>something in the connection that matches a threat defense signature </li> <li>malware, spyware or other content should be blocked</li> </ul> </ul> <strong>Please contact your administrator if you feel this is incorrect. </strong> </div> </body> </html>
"

**Comment by BBeran** [comment]
Your security software is not allowing traffic through that port. I am not an expert on McAfee so please refer to their documentation on how you can enable traffic through a specific port.
