### ISSUE TITLE
Tabpy installation question

### ISSUE THREAD

**Issue by knozaw** [tableau/TabPy#271]
Hello,

I installed python packages (i.e. networkx), tabpy-client, and tabpy-server using Anaconda navigators. 

![image](https://user-images.githubusercontent.com/23086503/56698800-01aa7d00-66a8-11e9-884a-63dc4232878b.png)

When I went to following directory: C:\Users\knozawa\AppData\Local\Continuum\anaconda3\envs\Tableau-Python-Server\Lib\site-packages\tabpy_server

I double clicked the startup.bat, but the command prompt immediately shut down.

So, I downloaded TabPy-0.4 zipfile from github, extracted it, and pasted it within the directory. C:\Users\knozawa\AppData\Local\Continuum\anaconda3\envs\Tableau-Python-Server\Lib\site-packages\tabpy_server

After double clicked the startup.bat within the TabPy-0.4 folder, it connected to port 9004. 

![image](https://user-images.githubusercontent.com/23086503/56699040-cceaf580-66a8-11e9-933b-32fdae17f50f.png)

However, when I tried to import the networkx using the calculated field within the tableau desktop, I've received this error message:
![image](https://user-images.githubusercontent.com/23086503/56699072-ee4be180-66a8-11e9-88bc-023491e63185.png)

I don't believe the TabPy setup was correct.  Does anyone know how to fix it?

Sincerely,
knozawa

**Comment by 0golovatyi** [comment]
@knozaw For any module to be available for `import` it needs to be installed in Python environment. You can confirm if networkx package is installed running the next command from the same command window you start TabPy from: `pip list`. If the package is not in the list you'll need to install it with `pip install networkx`.

TabPy setup doesn't install networkx because it doesn't use it. For all the packages which are not installed with TabPy you need to install them in your Python environment.

**Comment by knozaw** [comment]
@0golovatyi ,

Thank you very much! I could successfully install the networkx package using pip install networkx command.

Sincerely,
knozawa
