### ISSUE TITLE
An error occurred while communicating with the Predictive Service.

### ISSUE THREAD

**Issue by YipGwaisam** [tableau/TabPy#28]
Hi All,
     I would like to try Correlation coefficient analysis with Python on tableau.Then I create a new calculated field.
![image](https://cloud.githubusercontent.com/assets/26791402/24500970/3750e38a-157a-11e7-95c4-57dcf5a3eeec.png)
but tableau return the error :An error occurred while communicating with the Predictive Service.
![image](https://cloud.githubusercontent.com/assets/26791402/24501092/abf92382-157a-11e7-967e-98b1ddfb6fdc.png)

I want to know How to deal with this.
thanks very much for your help.

**Comment by BBeran** [comment]
Can you try changing your addressing settings for the calculation?

For example if you have [Date] as a dimension in the view, right click on the pill for this calculation in your sheet and select Edit Table Calculation from the context menu and then select Specific Dimensions from the list then check the box next to Date. If you want to send all of your data at once to Python, you may want to check all of the boxes in that list. Anything unchecked will be treated as a partition meaning Tableau will make a separate call with the data within that partition. E.g. if you want to compute correlation per product line, you would want to uncheck the product line box. You're getting this error since due to table calculation settings points are being sent to Python one at a time resulting in n - 2 = -1 degrees of freedom. 

I hope this helps.

Bora

**Comment by YipGwaisam** [comment]
it's solved! thank you!
