### ISSUE TITLE
Datetimes

### ISSUE THREAD

**Issue by bentheye** [tableau/TabPy#34]
Is there currently functionality around datetimes?  I couldn't put one in and bring it back. I was originally using a module called businesstimedelta, but the error is the same for a simple function such as the one below.  I have used tabpy successfully for integers, strings, and real.  If I'm way off base and datetimes do function, could you provide an example with a deployed function and if you have time a function located in the Tableau calculated field?  Thanks in advance for the help and for developing tabpy - the integration is extremely useful.

The below script gives me an non-existent endpoint error.

`import tabpy_client
import datetime

connection = tabpy_client.Client('http://localhost:9004/')

def string(x):
    x_str = str(x)
    x_dt = datetime.datetime.strptime(x_str, '%Y-%m-%d %H:%M:%S')
    x_dt_str = str(x_dt)
    return x_dt_str
    
connection.deploy('string', string, 'string -> datetime -> string', override = True)`

**Comment by BBeran** [comment]
Hi,
The error "Tableau Error: The endpoint you're trying to query did not respond. Please make sure the endpoint exists and the correct set of arguments are provided." indicates the endpoint didn't respond because it either doesn't exist or it failed to evaluate the request due to an exception e.g. it was expecting strings in a certain format to cast to dates but string parsing failed due to unexpected string format which is very likely the case here. 

I copy-pasted the function you have above into Tableau for debugging.

SCRIPT_STR("
x_str = str(_arg1)
x_dt = datetime.datetime.strptime(x_str, '%Y-%m-%d %H:%M:%S')
x_dt_str = str(x_dt)
return x_dt_str",MIN([Order Date]))

And this is the error I get

Error processing script
ValueError : time data "[u'2011-01-04', u'2011-01-07', u'2011-01-05']" does not match format '%Y-%m-%d %H:%M:%S'

Changed the data type of Order Date to DateTime

Then I get this error
ValueError : time data "[u'2011-01-04T00:00:00Z', u'2011-01-07T00:00:00Z', u'2011-01-05T00:00:00Z']" does not match format '%Y-%m-%d %H:%M:%S'

This gives you an idea about what the data looks like and what is failing. If you copy-paste the code into Tableau before publishing as TabPy endpoints you will get more transparent error messages.

OK. Now the working version given we know that data is being passed in the format '%Y-%m-%d for date and %Y-%m-%dT%H:%M:%SZ for datetime

SCRIPT_STR("import datetime
x_dt=[datetime.datetime.strptime(dx, '%Y-%m-%dT%H:%M:%SZ') for dx in _arg1]
x_dt_str = [x.strftime('%Y-%m-%dT%H:%M:%S') for x in x_dt]
return x_dt_str",MIN([Order Date]))

Since we are operating over a list of dates I am using a list comprehension to loop through each can convert to date in a nice, compact way.

Last step is not meaningful since it converts back to string but it mimics what your code is doing essentially but using but using a different function to create a formatting string from datetime we created earlier.

I hope this helps.

~ Bora
