### ISSUE TITLE
Tabpy & Tableau: Successfully deployed function, but still get an error occurred while communicating with the External Service

### ISSUE THREAD

**Issue by alitkie** [tableau/TabPy#406]
**Context:** My team has created a recommender system that predicts the flights least likely to be delayed in the US when inputing 5 parameters (arrival time, origin, destination, airline, threshold).

**Problem:** I run the python script in Jupyter notebook and it runs successfully. I then deploy the function. I have checked my local host end points, and I can see the function has been deployed successfully. I have then created the 5 parameters mentioned above in Tableau, the first four being strings and the threshold being an integer. I have also created the calculated field in Tableau, with the following code:

SCRIPT_STR("return tabpy.query('FlightPredictorV1',_arg1,_arg2,_arg3,_arg4,_arg5)['response']",
[arrival_time], [origin], [destination], [airline], [threshold])

**Error:** When I try apply this calculated field by dragging it into the Tableau sheet, I get the following error:

An error occurred while communicating with the External Service.
Error Code: 6116DD27
Error processing script
The endpoint you're trying to query did not respond. Please make sure the endpoint exists and the correct set of arguments are provided.

**Attached:**
- Screenshot of the recommender system and code to deploy it
- Screenshot of endpoints 
- Screenshot of the calculated in field in Tableau with parameters created on the righthand side
- Screenshot of error message
- What the recommender looks like in Jupyter Notebook 

<img width="336" alt="Screenshot 2020-04-05 at 13 34 47" src="https://user-images.githubusercontent.com/48287225/78473683-df87fe80-7742-11ea-94d4-f53bb6571426.png">
<img width="1440" alt="Screenshot 2020-04-05 at 13 36 16" src="https://user-images.githubusercontent.com/48287225/78473687-e4e54900-7742-11ea-8460-744223f3b37c.png">
<img width="1440" alt="Screenshot 2020-04-05 at 13 36 54" src="https://user-images.githubusercontent.com/48287225/78473689-e7e03980-7742-11ea-9604-9f29cf3fe5e0.png">
<img width="1223" alt="Screenshot 2020-04-05 at 13 38 14" src="https://user-images.githubusercontent.com/48287225/78473693-ec0c5700-7742-11ea-9ce4-a06094825e56.png">
<img width="868" alt="Screenshot 2020-04-05 at 13 42 15" src="https://user-images.githubusercontent.com/48287225/78473769-6b9a2600-7743-11ea-81b3-d4bfb39761f4.png">

**Comment by nmannheimer** [comment]
Hi @alitkie the first thing I would check is that you're processing the inputs correctly in your code. Parameters are passed from Tableau as Python lists of length 1. So an arrival time sent to your code from Tableau will look something like ["18/11/2020 20:30"]. If you're trying to parse it directly as a string, your code would need to handle it as something like hour = arrival_time[0][11:15].

You can also use print statements to debug your code by creating breakpoints at each step.

**Comment by 0golovatyi** [comment]
@alitkie Is it possible with Tableau you are connected to a different TabPy instance then you deployed the function to?

**Comment by alitkie** [comment]
> Hi @alitkie the first thing I would check is that you're processing the inputs correctly in your code. Parameters are passed from Tableau as Python lists of length 1. So an arrival time sent to your code from Tableau will look something like ["18/11/2020 20:30"]. If you're trying to parse it directly as a string, your code would need to handle it as something like hour = arrival_time[0][11:13].
> 
> You can also use print statements to debug your code by creating breakpoints at each step.

@nmannheimer thanks for the help. The inputs are correct I think. I am passing the deployed function strings for each input, besides threshold which I am passing an integer. Those are the same parameters I use in the Jupyter notebook itself. So it is meant to be passed as ["18/11/2020 20:30"]. 

How would I print statements to see what is wrong?
Thanks again

**Comment by alitkie** [comment]
> @alitkie Is it possible with Tableau you are connected to a different TabPy instance then you deployed the function to?

@0golovatyi Thanks for the help. I am afraid not. Because when I try call upon the other functions deployed i.e.DiangosticDemo, then it works just fine. So it is specific to the example I gave.
Thanks again though

**Comment by 0golovatyi** [comment]
@alitkie What do you see in TabPy log when calling the model from Tableau?

**Comment by nmannheimer** [comment]
@alitkie looking at your code, specifically the first line: hour = arrival_time[11:13] you are slicing directly into the variable to extract components of the string. Since TabPy is sending the parameter string or int values to your code in a list (not as a raw string which your code seems to expect), your code is actually trying to slice items out of the list, which is probably resulting in an issue with the index being out of range, resulting in Python with hour = [ ] which is causing problems later on, along with the other areas where you try and extract components from the string. Essentially this is happening: 

![image](https://user-images.githubusercontent.com/24558045/78710553-5ef40a00-78ca-11ea-9921-4b1788556cdb.png)

So to correct for it, you need to extract the string out of the list any time you are trying to parse the string (or int) directly. To confirm that this is the error, you could hard code in string values into a version of your functions and deploy it. If it returns a constant result, you will be able to confirm that it's how the inputs are being handled that's the issue.

**Comment by alitkie** [comment]
> @alitkie looking at your code, specifically the first line: hour = arrival_time[11:13] you are slicing directly into the variable to extract components of the string. Since TabPy is sending the parameter string or int values to your code in a list (not as a raw string which your code seems to expect), your code is actually trying to slice items out of the list, which is probably resulting in an issue with the index being out of range, resulting in Python with hour = [ ] which is causing problems later on, along with the other areas where you try and extract components from the string. Essentially this is happening:
> 
> ![image](https://user-images.githubusercontent.com/24558045/78710553-5ef40a00-78ca-11ea-9921-4b1788556cdb.png)
> 
> So to correct for it, you need to extract the string out of the list any time you are trying to parse the string (or int) directly. To confirm that this is the error, you could hard code in string values into a version of your functions and deploy it. If it returns a constant result, you will be able to confirm that it's how the inputs are being handled that's the issue.

Thanks for the detailed explanation, that makes a lot of sense now. Appreciate it.

I do believe this could be the problem then... What would I need to run in order to fully correct this? Would I have to change how I call the function in Tableau to fix it?

Thanks

**Comment by nmannheimer** [comment]
You'll just need to write your code to handle lists instead of raw variables. Since you're using parameters from Tableau, the lists will be constant, so you can just pull the value at index 0. This means just taking the first value in your variable[0]. ie 'string' == ['string'][0]. 

You can test this in your jupyter notebook by just making the inputs to your functions lists that contain the strings/ints you're suing and testing/debugging there.

**Comment by 0golovatyi** [comment]
@alitkie were you able to resolve the issue?
