### ISSUE TITLE
Why does TabPy can't find endpoints of my function??

### ISSUE THREAD

**Issue by alamhanz** [tableau/TabPy#50]
I have successfully deployed the function, but the tableau pop this error,

`The endpoint you're trying to query did not respond. Please make sure the endpoint exists and the correct set of arguments are provided.`

what is happen here??

**Comment by BBeran** [comment]
It could be failing because the code fails to run e.g. because incorrect arguments were passed, data types are not expected.... If you could share the add function definition and how you're calling it from Tableau (most importantly type of data being passed -e.g. integer, float-, aggregations used -is it attr or min,max,avg..- and what does the visualization look like? -what dimensions are in the view and what is being used for addressing/partitioning setting for the calculation-), we should be able to get to the bottom of this quickly.

**Comment by BBeran** [comment]
Since I haven't heard about this issue in about 2 weeks, I will resolve assuming that the suggestion worked as expected. Please reactivate if the issue persists.
