### ISSUE TITLE
Install setup.bat failure

### ISSUE THREAD

**Issue by Chaosliuya** [tableau/TabPy#58]
![image](https://user-images.githubusercontent.com/32156174/30681687-2a8a45fe-9ed9-11e7-9518-3b83b21ee756.png)
![image](https://user-images.githubusercontent.com/32156174/30681698-35bb5314-9ed9-11e7-84f9-8ce977aceca9.png)

**Comment by BBeran** [comment]
The error indicates a network issue. Your computer is unable to access PyPI which is the package repository for Python. It could be your company firewall. Did you try it from a different network?

**Comment by Chaosliuya** [comment]
I am typing the pypi in the browser without any issue, can see all the
file. Would u able advice what should I do?

2017-09-21 18:59 GMT+08:00 BBeran <notifications@github.com>:

**Comment by BBeran** [comment]
When you hit PyPI web page, browser is using a different port. Most likely 80 or 8080. Since browser use is extremely common, communication through those ports are probably unlocked. I believe pip uses port 3128. Opening this port through firewall can work but there could be other security limitations on your work computer.

It is best to talk to your IT guy to figure out the optimal solution.  Most likely you have a proxy server and need to set http_proxy and https_proxy environment variables before you run the setup. But there could be more to it based on your corporate security policies. If your firewall requires ssl verification you'll need to set --trusted-host flag as well with pypi.python.org.

Again it is best to talk to your IT guy.

**Comment by Chaosliuya** [comment]
hi
If I ask it enable http://repo.continuhm.io/pkgs/pro/noarch/, issue will be
solve, right?
As the error indicate this website cannot be accessed. Thx.

Regards
Ya

2017-09-22 12:30 GMT+08:00 BBeran <notifications@github.com>:

**Comment by Chaosliuya** [comment]
Have changed the proxy set=up and now installed successfully. thx
