### ISSUE TITLE
Issue connecting external server in tableau

### ISSUE THREAD

**Issue by mansjun** [tableau/TabPy#60]
after I install tabpy-server in my machine, I go to "help"-->"manage external service connection" and set up server by use localhost and 9004, when I test connection, I get below error, what I need to do to connect the server? thanks

RServe: An error has occurred during connection to localhost:9004: No connection could be made because the target machine actively refused it ExtSvc: Failure when receiving data from the peer

**Comment by BBeran** [comment]
Can you connect to it by typing http://localhost:9004 in your browser window?

Either service isn't running or port is blocked by your operating system or firewall.

**Comment by mansjun** [comment]
yes, the link is running and tableau logo shows up.
Do you know how can I check if the port is blocked by the system or firewall? 

I reboot the laptop, and this time the error says:
External Service: Rserve is busy or not responding. Failed to create socket to Rserve. ExtSvc: Timeout was reached

**Comment by BBeran** [comment]
This might help
https://www.windowscentral.com/how-open-port-windows-firewall

On my computers, both on Mac and Windows 7, the moment it starts running for the first time I got a pop up asking whether I want to give the process network access and I hit OK and everything worked. I believe this is the typical experience since we don't get this problem reported very often.

You may also want to create an inbound rule to enable the python process through using the same firewall configuration dialog.

TabPy service won't start automatically if you restart your machine. This is why you're getting a different error after restarting your laptop. You will need to start it manually using [Your Python package installation path here]/tabpy_server/startup.bat on Windows and tabpy_server/startup.sh on Mac or Linux.

**Comment by mansjun** [comment]
I followed the link and create the inbound rule, but still get the same error.

**Comment by mansjun** [comment]
by the way, I am using 10.1.9 version

**Comment by BBeran** [comment]
If by same error you mean "External Service: Rserve is busy or not responding. Failed to create socket to Rserve. ExtSvc: Timeout was reached"

You will need to start tabpy manually.

**Comment by mansjun** [comment]
I start tabpy by clicking startup.bat and I believe it starts successfully but still get error.

**Comment by DenissePerez** [comment]
Hi, I have a question... Out tabpy is being istalled on a different machine (another server running it) seems like they've installed it as localhost too, so I'm unable to reach it.. sould be more like  'different.server.com:9004', right?

Or how is it done for this case?

BTW: I've sucessuflly installed and used it as a local.

Thanks in advance.

**Comment by BBeran** [comment]
That is correct. You need to use the hostname or IP address.

**Comment by mansjun** [comment]
yes, I run it from command line and it says
web service listening on prot 9004, 
same thing as I open it in folder.
