### ISSUE TITLE
connect Tableau to TabPy 

### ISSUE THREAD

**Issue by ranjithgoud24** [tableau/TabPy#77]
I just have the Tabpy server running on localhost:9001.
I can see Tableau logo on web browser. But the tableau connection says below error
RServe: IPC_Network::Resolve(hostname="http://localhost"): The requested name is valid, but no data of the requested type was found ExtSvc: 503:

Can you please help?

Thanks
Ranjith

**Comment by tmartintableau** [comment]
Hi Ranjith,

Based on the error, it looks like Tableau is trying to connect to an RServe instance. This is possibly because you have the wrong port set on the Tableau side. Have you tried changing the port from the External Service Connection dialog? From the main window, Help -> Settings and Performance -> Manage External Services Connection. The port in this dialog should match the port that the TabPy server is running on (9001).

If that doesn't work, can you post a screenshot of your External Service Connection dialog?

Thanks!

Tyler

**Comment by nmannheimer** [comment]
Closing this issue. Ensuring that the ports line up should resolve the issue. Similarly, TabPy will only be accessible in Tableau 10.1 and newer.
