### ISSUE TITLE
TypeError: unsupported operand types for Unicode and unicode

### ISSUE THREAD

**Issue by ayushvaishya** [tableau/TabPy#83]
I am trying the following code in tableau via tabpy and I am getting a type error while the code seems to be perfectly fine 

SCRIPT_REAL("import pandas as pd
import numpy as np
s = _arg1
f = _arg2
dates = pd.DataFrame(np.transpose(np.array(s))).values
SALES= pd.DataFrame(f)
#dates = pd.to_datetime(dates)   
y = ((dates - dates.min())/np.timedelta64(1,'D'))
from sklearn.ensemble import RandomForestRegressor 
regressor = RandomForestRegressor(n_estimators = 300)
regressor.fit(y,SALES)
y_pred = regressor.predict(y)
",ATTR([Order Date]),ATTR([Sales]))

The error is : Unsupported operand types for -: 'unicode' and 'unicode'
Date is in normal datetime format and sales is 3 digit integer column

**Comment by sbabayan** [comment]
From the error message it sounds like Sales might be a string of ints rather an an int itself. I believe the pandas library has a to_numeric function (similar to to_datetime), there's more information outlined in the link here: https://pandas.pydata.org/pandas-docs/stable/generated/pandas.to_numeric.html

**Comment by BBeran** [comment]
Most likely ATTR is returning * and being treated as NULL. This might happen if Order Date is not a dimension in the view. If for a given Order Date there is more than one Sale (which is highly likely) ATTR(Sales) will also return *.  For Sale, you should be using SUM(Sales) or AVG(Sales) etc. to avoid this problem. So first things to check is, remove this calculation from the view, add ATTR(Order date) and ATTR(Sales) as individual pills and see if you're getting any *.  If you don't want aggregations to happen, you can turn on aggregations from analysis menu. 

Also this code isn't valid since it doesn't return anything (no return statement).

You can learn more about how the process works here.

https://community.tableau.com/docs/DOC-10856

There are lots of examples of returning predictions from scikit learn models on this Github repository and here

https://www.tableau.com/about/blog/2017/1/building-advanced-analytics-applications-tabpy-64916
