### ISSUE TITLE
Tableau's documentation adjustments (Tableau communicates with Python by lists)

### ISSUE THREAD

**Issue by lojacobs** [tableau/TabPy#99]
By playing around, I discovered that the documentation in Tableau isn't up to date.

The examples aren't working because in Python 3.6, the "map" function return a map object whereas Tableau need to receive a list. Thus, **we need to list( ) the map function** to return a list.

Also, It should be good to demonstrate how to use Tableau's Parameters.

In my example below, the [Filter for regex] is a **String Parameter** inside Tableau. Because Tableau send to Python the parameter as a list with the same value for every row in the visual, we need to limit the parameter to only 1 variable with the **[0]** to get the first argument of the list.

```
SCRIPT_BOOL(
"import re
return list(map(lambda x: bool(re.search(_arg1[0],x)),_arg2))
",[Filter for regex],Attr([Customer Name])
)
```

From this experimentation, I assume that Tableau will always want to receive a list back to match the rows as well as will always send to Python lists. (so, we have to adjust in Python for that)

PS: it's easier to use the Tableau's regex functions but it's a good way to test the way Tableau is working with Python ;-)

**Comment by Sidneypeacock** [comment]
Well spotted @lojacobs this was just the thing is was struggling with right now, how comes all the samples don't actually work! 

Wrapping list()  seemed to work on some of my samples, but I still can't get titlecase to work, even with the list...

Here's my calculated field (constraints is just a sentence of people moaning)

SCRIPT_STR("from titlecase import titlecase 
return list(map(titlecase,_arg1))", ATTR([constraints?]))

and now after adding the list() wrap around the map I get the following error
**expected string or bytes-like object**

I'm really on using this as a sample to test connections and show that TabPy does actually work.
I'm pretty new to python and I admit I'm making some schoolboy syntax errors, but this looks right to me... It's copied from the blog!

Any help is appreciated, thanks in advance...

**Comment by Sidneypeacock** [comment]
I sorted it! 

Apologies - makes perfect sense when you think about it...

Constraints contained NULL values, so by excluding them, it works like a dream.

**Comment by lojacobs** [comment]
Good to know that NULL values aren't handle! I would expect that Tableau sends NaN to Python...

Also, take care of the dimensions that you're using in the Table Calculation inside Tableau. I discover that that could also break your python calculation like this one:

The code in Python with the Client Deployement:
```
import tabpy_client
client = tabpy_client.Client('http://localhost:9004/')

def clustering(x, y):
    import numpy as np
    from sklearn.cluster import KMeans
    from sklearn.preprocessing import StandardScaler
    X = np.column_stack([x, y])
    X = StandardScaler().fit_transform(X)
    db = KMeans(3).fit(X)
    return db.labels_.tolist()

client.deploy('clustering',
                clustering,
                'Returns cluster Ids for each data point specified by the pairs in x and y',
                override=True)
```

The calculation inside Tableau:
```
SCRIPT_INT(
"return tabpy.query('clustering',_arg1,_arg2)['response']"
, sum([Profit]),sum([Sales])
 )
```
AND you have to use all the dimensions or only the one that defines your level of detail of your visual:
![image](https://user-images.githubusercontent.com/1313588/39248615-939112fe-486a-11e8-9234-e5985700028c.png)

**Comment by nmannheimer** [comment]
To explain a little bit more about how TabPy handles data from Tableau: values are passed and expected to return as a list. NULLs from Tableau are converted to the Python None type. This can cause issues when a model or function does not expect or have the ability to handle Python None type values.

Regarding partitioning and addressing table calculation dimensions in Tableau: a separate call to the TabPy server for each combination of partitioned dimensions. In the example above, separate clusters are being computed for each window in the view ie Consumer/Furniture or Corporate/Office Supplies. Having the box checked next to a dimension, as is the case for Customer Name, signals to the calculation not to partition on that dimension. In the case above, this makes sense because we would not want to send a separate call for each customer. This would result in ~9500 calls in Superstore and each would have a sample size of 1, resulting in all failed clusters or 9500 unique clusters depending on the model. 

There are cases when it makes sense to put everything on addressing (check all boxes), for example text data where we are running sentiment analysis. The results of a given sample don't depend on other samples and checking all boxes will result in only a single server call being made, which will improve performance.

I'm going to close this issue since the underlying questions have been addressed. For further question on TabPy functionality, please reach out to us in the [Tableau forums](https://community.tableau.com/community/forums/externalservices)!

**Comment by BBeran** [comment]
You can find more information about how integration works on TabWiki
https://community.tableau.com/docs/DOC-10856
